### ISSUE TITLE
Solarized light colors

### ISSUE THREAD

**Issue by domoritz** [jorgebucaran/metrofish#1]
The color choices for solarized light don't work as well as for solarized dark. For instance, the black font over the red background is hard to read in the light theme. I also wonder why the `ipython-vega` string is lighter in solarized dark but not in solarized light. 

Light color theme

![screen shot 2016-05-17 at 13 54 56](https://cloud.githubusercontent.com/assets/589034/15338951/fec0a984-1c36-11e6-9cb7-5f5e435d67e9.png)

Dark color theme

![screen shot 2016-05-17 at 13 52 02](https://cloud.githubusercontent.com/assets/589034/15338954/00becd06-1c37-11e6-8b2f-155480b29c59.png)

**Comment by ghost** [comment]
This is an issue with the solarized colors actually, as Metro is simply using `white`. If you change the regular `white` (not bright white) in your light solarized terminal settings you could adjust it to your liking.

AFIK there is no way to determine if we are inside light / dark mode to pick other colors.

**Comment by domoritz** [comment]
Hmm, it doesn't seem to change anything in iterm 2 (2.9). 

<img width="364" alt="screen shot 2016-05-17 at 22 01 07" src="https://cloud.githubusercontent.com/assets/589034/15347934/eacce3c2-1c7a-11e6-9177-2f4b48ef9fc8.png">
<img width="195" alt="screen shot 2016-05-17 at 22 01 03" src="https://cloud.githubusercontent.com/assets/589034/15347935/ece7c212-1c7a-11e6-84f4-fb8cf3613894.png">

**Comment by ghost** [comment]
<img width="499" alt="screen shot 2016-05-18 at 2 33 09 pm" src="https://cloud.githubusercontent.com/assets/8317250/15348400/7c44ff4e-1d05-11e6-91e4-ce9d383c325c.png">

iTerm's 2 default light solarized (without changes)

<img width="918" alt="screen shot 2016-05-18 at 2 33 20 pm" src="https://cloud.githubusercontent.com/assets/8317250/15348401/80cbbe22-1d05-11e6-9870-37c7331b94c3.png">

**Comment by ghost** [comment]
<img width="502" alt="screen shot 2016-05-18 at 2 34 25 pm" src="https://cloud.githubusercontent.com/assets/8317250/15348422/b156dd06-1d05-11e6-9a98-3f87c8a9b75c.png">

Same light solarized, changing the bright white to some cyan this time.

<img width="185" alt="screen shot 2016-05-18 at 2 34 37 pm" src="https://cloud.githubusercontent.com/assets/8317250/15348423/b3750586-1d05-11e6-8398-e7d2aaefea0f.png">

**Comment by domoritz** [comment]
Hmm, something in my setup must be different. Maybe I have some leftovers from `fish_config`. I'll see what I can find now that I know to expect.

**Comment by ghost** [comment]
@domoritz Thanks, one more thing. I took those screenshots in my current setup using fish 2.3.
